/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'U6015446' at '9/11/17 2:36 PM' with Gradle 3.0
 *
 * @author U6015446, @date 9/11/17 2:36 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
